# This program returns a CSV file. Each row contains the frequency distribution by topic of the comments left
# from Edgeryders users in modularity partition class i to modularity partition class j.
# When i = j the distribution maps to intra-community edges in the Edgeryders network.
# The program accepts as input the CSV file generated by the program called comment_data_extractor.py, 
# less the headers.

import csv

to_filename = '/Users/albertocottica/Documents/PhD/MyPhDdata/Extraction 2012-12-05-1623/frequency_counts.csv'
to_file = open(to_filename, 'w', newline = '')

bigtable_filename = '/Users/albertocottica/Documents/PhD/MyPhDdata/Extraction 2012-12-05-1623/exported.csv'
bigtable_data = open(bigtable_filename, 'r', encoding = 'utf-8')

# Initialize accumulators

frequencies_table = []

for i in range (15):
        frequencies_table.append([])
        for j in range(15): 
                frequencies_table[i].append([])
                for c in range(9):
                        frequencies_table[i][j].append(0)

# now populate the table


# we need to store the computed partitions somewhere to avoid the need to
# re-open the file at each comment iteration
#------CHANGED FROM HERE
# saved_bigtable_data = {} # this will be a hash using the comment id as a key
bigtable_data_reader = csv.reader(bigtable_data)

for row in bigtable_data_reader:
        author_community = int(row[1])
        recipient_community = int(row[4])
        topic = int(row[3][:2])
        frequencies_table[author_community][recipient_community][topic] = frequencies_table[author_community][recipient_community][topic] + 1
 
#   saved_bigtable_data[int(row['comment ID'])] = row




# for k in saved_bigtable_data:
#       author_community = int(saved_bigtable_data[k]['author community'])
#       recipient_community = int(saved_bigtable_data[k]['recipient community'])
#       topic = int(saved_bigtable_data[k]['topic'][1])
#       frequencies_table[author_community][recipient_community][topic] = frequencies_table[author_community][recipient_community][topic] + 1

# Write frequencies_table into a file.

file_writer = csv.writer(to_file)

# Write the header of the CSV file
file_writer.writerow(['From community','To community','00 - Undefined','01 - Bootcamp','02 - Making a living', '03 - We, the people', '04 - Caring for commons', '05 - Learning', '06 - Living together', '07 -Finale', '08 - Resilience'])

# Write all the rows

for a in range(len(frequencies_table)):
        for b in range(len(frequencies_table[a])):
                longrow = [a, b]
                for index in range (9):
                        longrow.append (frequencies_table[a][b][index])
                file_writer.writerow(longrow)

to_file.close()
